name: PyLint Ultroid
on:
  push:
    branches:
        - patch-1
        - patch-2
    paths:
    - "**.py"
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          cache: "pip"
      - name: Install Python lint libraries
        run: pip install autopep8 autoflake isort black
      - name: Check for showstoppers
        run: |
          autopep8 --verbose --in-place --recursive --aggressive --aggressive pyUltroid/*.py
          autopep8 --verbose --in-place --recursive --aggressive --aggressive assistant/*.py
          autopep8 --verbose --in-place --recursive --aggressive --aggressive assistant/manager/*.py
          autopep8 --verbose --in-place --recursive --aggressive --aggressive plugins/*.py
      - name: Remove unused imports and variables
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports pyUltroid/*.py
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports assistant/*.py
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports assistant/manager/*.py
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports plugins/*.py
      - name: lint with isort and black
        run: |
          isort --profile black pyUltroid/*.py
          black --fast pyUltroid/*.py
          isort assistant/*.py
          isort assistant/manager/*.py
          black --fast assistant/*.py
          black assistant/manager/*.py
          isort plugins/*.py
          black --fast plugins/*.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'pylint: auto fixes'
          commit_options: '--verify'
          repository: .
          commit_user_name: ufoptg
          commit_user_email: ufperth@protonmail.com
          commit_author: ufoptg <ufperth@protonmail.com>
